// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Category struct {
	ID     uuid.UUID
	Name   string
	UserID uuid.UUID
}

type Note struct {
	ID        uuid.UUID
	Title     string
	Body      string
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type NoteCategory struct {
	NoteID     uuid.UUID
	CategoryID uuid.UUID
}

type User struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Username     string
	Password     string
	Token        sql.NullString
	RefreshToken sql.NullString
}
