// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: notes.sql

package database

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (id, title, body, user_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, body, user_id, created_at, updated_at
`

type CreateNoteParams struct {
	ID        uuid.UUID
	Title     string
	Body      string
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNoteById = `-- name: GetNoteById :one
SELECT n.id, n.title, n.body, n.user_id, n.created_at, n.updated_at, json_agg(c) as categories
FROM notes n
LEFT JOIN note_categories nc ON nc.note_id = n.id
LEFT JOIN categories c ON c.id = nc.category_id
WHERE n.id = $1 AND n.user_id = $2
GROUP BY n.id
`

type GetNoteByIdParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetNoteByIdRow struct {
	Note       Note
	Categories json.RawMessage
}

func (q *Queries) GetNoteById(ctx context.Context, arg GetNoteByIdParams) (GetNoteByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getNoteById, arg.ID, arg.UserID)
	var i GetNoteByIdRow
	err := row.Scan(
		&i.Note.ID,
		&i.Note.Title,
		&i.Note.Body,
		&i.Note.UserID,
		&i.Note.CreatedAt,
		&i.Note.UpdatedAt,
		&i.Categories,
	)
	return i, err
}

const getNotesByUser = `-- name: GetNotesByUser :many
SELECT
  n.id, n.title, n.body, n.user_id, n.created_at, n.updated_at,
  json_agg(c) as categories
FROM
  notes n
LEFT JOIN
  note_categories nc ON nc.note_id = n.id
LEFT JOIN
  categories c ON c.id = nc.category_id
WHERE
  n.user_id = $1
  AND ($2 IS FALSE OR nc.category_id = ANY($3::uuid[]))
GROUP BY
  n.id
ORDER BY
  n.created_at DESC
`

type GetNotesByUserParams struct {
	UserID  uuid.UUID
	Column2 interface{}
	Column3 []uuid.UUID
}

type GetNotesByUserRow struct {
	Note       Note
	Categories json.RawMessage
}

func (q *Queries) GetNotesByUser(ctx context.Context, arg GetNotesByUserParams) ([]GetNotesByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getNotesByUser, arg.UserID, arg.Column2, pq.Array(arg.Column3))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotesByUserRow
	for rows.Next() {
		var i GetNotesByUserRow
		if err := rows.Scan(
			&i.Note.ID,
			&i.Note.Title,
			&i.Note.Body,
			&i.Note.UserID,
			&i.Note.CreatedAt,
			&i.Note.UpdatedAt,
			&i.Categories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNoteTitleBody = `-- name: UpdateNoteTitleBody :one
UPDATE notes
SET title = $1, body = $2, updated_at = $3
WHERE id = $4
RETURNING id, title, body, user_id, created_at, updated_at
`

type UpdateNoteTitleBodyParams struct {
	Title     string
	Body      string
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) UpdateNoteTitleBody(ctx context.Context, arg UpdateNoteTitleBodyParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNoteTitleBody,
		arg.Title,
		arg.Body,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
