// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: note_categories.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createNoteCategory = `-- name: CreateNoteCategory :one
INSERT INTO note_categories (note_id, category_id)
VALUES ($1, $2)
RETURNING note_id, category_id
`

type CreateNoteCategoryParams struct {
	NoteID     uuid.UUID
	CategoryID uuid.UUID
}

func (q *Queries) CreateNoteCategory(ctx context.Context, arg CreateNoteCategoryParams) (NoteCategory, error) {
	row := q.db.QueryRowContext(ctx, createNoteCategory, arg.NoteID, arg.CategoryID)
	var i NoteCategory
	err := row.Scan(&i.NoteID, &i.CategoryID)
	return i, err
}
